version: "2"
services:
  api:
    container_name: api
    build: .
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - app
  db:
    container_name: db
    image: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USERNAME=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app

volumes:
  postgres-data:

networks:
  app:
    driver: bridge
